apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-webhook-sa
  labels:
    app: admission-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-webhook-cr
  labels:
    app: admission-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-webhook-crb
  labels:
    app: admission-webhook
subjects:
  - kind: ServiceAccount
    name: admission-webhook-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-webhook-cr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-deployment
  labels:
    app: admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook
  template:
    metadata:
      labels:
        app: admission-webhook
    spec:
      serviceAccount: admission-webhook-sa
      containers:
        - name: admission-webhook
          image: kimoqi/admission-webhook-example:v1
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-svc
  labels:
    app: admission-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-webhook
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-cfg
  labels:
    app: admission-webhook
webhooks:
  - name: required-labels
    clientConfig:
      service:
        name: admission-webhook-svc
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJek1Ea3hOekEzTURNME1sb1hEVE16TURreE5UQTNNRE0wTWxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTndMClIrM1ljSlRZT1M1RFJscHV4b2lxVUgwY2gwWlVnR053MmExQU9GUnBMbmpQK3N4NERxKzQ3dG5yby9ndTlGbUUKd1RJSk9YRnRtTTBpbXNUbmkvOG5kd3NVWmppeFQxTHkrK0YxSVhyVUgxK3R3V1lpQ252MmlISG5qU3dWYnNtLwpXYytBWHlIUFFIRmQ4dDhKL003NXBFaDR2eUNwbzNuUzJjWXpWMWFZQytKcGdZdGEzQXBPSFoySE1vMXJ5ODh2Cmt5K2NtaTVBSEkybG9uSndjQmd4S2FtSk5xMHFyUmcyOFZGSTBYWlBNSjNob3ZnL1BJWFlibXg3L0ZNdGwxbWwKZHFJekVzNVpHbS84NE1jQzhQcm1qS0VOblcyL0o1bVpWdm50R1UzVk0zUG9lN2hJaGtleDlnWkkwaTdFUmxNMgphOHZSem1WOVg4TFllNkcyMkdFQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRQUNRWmlnZExwYzViQ3E4OWtEZ3RlUTFrcGVEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFTWXNYTUppTwpoSndIQTk5VzZZSWR3WUlMQ2hDY3FiOXhOdnRBWis5TlBnZ2RPcmlPL3RSeU9TdzZIQldadHdRRStmT040cW9GCnJkVmJaaURyMTlGNEdFL2I1ZmNwYkdETDhQdUFTODJwL1pIb1hzc0VzQVRLRFdlNUZGQXdYT09TNU02UDUzelUKMXJFTGZGRFI2ZkVXSXJzc1piN2g0cG1tQ0drN0RZeENIdjlHZExnV1h2Vmw1VzIvdkhrbFpwSmdrZWZvaEVPbgpmS3l2VzM2QkN2TThqUmw4VTJHYk8rUGR2SjBXSG5Rc3l3OHVRb3o1NFhQdlpFdzBBT09lbFkya1dsR3lUSGdpCjNoaVRKUU9EbVRYeVBoL1UzYWRZL04xajJobWJ2OWt5MEI0NHRzVFhtRVNBNWRzOC81cWV1SStKeG16Y0Z4a0QKT2lRZmM2S1RwSFlpWXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments", "services"]
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
